/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8LLPmfIQR2J
 */
"use client";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { useSession } from "next-auth/react";
import { api } from "@/trpc/react";

export function InnerApplication_form() {
  const { status, data: session } = useSession();
  const applytoPilot = api.auth.Addaccount.useMutation({
    onSuccess: () => {
      console.log("OP SUCCESS");
    },
  });

  function ApplyToAirlineProgran(event: React.SyntheticEvent) {
    event.preventDefault();
    const email = (document.getElementById("email") as HTMLInputElement).value;
    const password = (document.getElementById("password") as HTMLInputElement)
      .value;

    applytoPilot.mutate({
      email: email,
      password: password,
    });
  }

  return (
    <main className="px-4 py-8 md:px-6 lg:px-8">
      {status === "unauthenticated" && (
        <div className="mx-auto flex h-screen max-w-3xl items-center justify-center ">
          <CardHeader className="bg-red-600">
            <CardTitle className="text-white">ACCESS DENIED!</CardTitle>
            <CardDescription className="text-white">
              LOG IN TO GAIN ACCESS TO THIS PAGE{" "}
            </CardDescription>
          </CardHeader>
        </div>
      )}
      {status === "authenticated" && (
        <Card className="mx-auto max-w-3xl">
          <CardHeader>
            <CardTitle>Apply to Airline Program</CardTitle>
            <CardDescription>
              Please fill out the form below. All fields are required.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="Enter your name" required={true} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="dob">Date of Birth</Label>
              <Input id="dob" required={true} type="date" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="gender">Gender</Label>
              <Select>
                <SelectTrigger id="gender">
                  <SelectValue placeholder="Select" aria-required={true} />
                </SelectTrigger>
                <SelectContent position="popper">
                  <SelectItem value="male">Male</SelectItem>
                  <SelectItem value="female">Female</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Phone</Label>
              <Input
                id="phone"
                placeholder="Enter your phone number"
                required={true}
                type="tel"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                placeholder="Enter your email"
                required={true}
                type="email"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="driver-license">
                Driver{"'"}s License Number
              </Label>
              <Input
                id="driver-license"
                placeholder="Enter your driver's license number"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="state">State</Label>
              <Input
                id="state"
                placeholder="Enter your state"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="airline">Airline</Label>
              <Input
                id="airline"
                placeholder="Enter your airline"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="employee-id">Airline Employee ID</Label>
              <Input
                id="employee-id"
                placeholder="Enter your airline employee ID"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="job-title">Job Title</Label>
              <Input
                id="job-title"
                placeholder="Enter your job title"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="airline-id-image">Airline ID Image</Label>
              <Input id="airline-id-image" required={true} type="file" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="emergency-contact-name">
                Emergency Contact Name
              </Label>
              <Input
                id="emergency-contact-name"
                placeholder="Enter emergency contact name"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="emergency-contact-address">
                Emergency Contact Address
              </Label>
              <Input
                id="emergency-contact-address"
                placeholder="Enter emergency contact address"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="emergency-contact-phone">
                Emergency Contact Phone Number
              </Label>
              <Input
                id="emergency-contact-phone"
                placeholder="Enter emergency contact phone number"
                required={true}
                type="tel"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="emergency-contact-relationship">
                Emergency Contact Relationship
              </Label>
              <Input
                id="emergency-contact-relationship"
                placeholder="Enter emergency contact relationship"
                required={true}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="referred-by">Referred By</Label>
              <Input
                id="referred-by"
                placeholder="Enter referred by"
                required={true}
              />
            </div>
          </CardContent>
          <CardFooter>
            <Button className="ml-auto">Submit</Button>
          </CardFooter>
        </Card>
      )}
    </main>
  );
}
